---
- name: Setup
  hosts: 127.0.0.1
  connection: local
  become: true
  become_user: root
  environment:
    HOME: '/home/thiago'
  tasks:
    - name: Install basepackages
      apt:
        name:
          - xclip
          - vim
          - fzf
          - tmux
        state: present

    - name: Add spotify signing key
      apt_key:
        url: https://download.spotify.com/debian/pubkey_0D811D58.gpg
        state: present

    - name: Add Spotify repository
      apt_repository: 
        repo: deb http://repository.spotify.com stable non-free
        filename: spotify-client
        state: present

    - name: Install spotify
      apt:
       name: spotify-client
       state: present

    - name: Add chrome signing key
      apt_key:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub        
        state: present

    - name: Add chrome repository
      apt_repository: 
        repo: deb http://dl.google.com/linux/chrome/deb/ stable main
        filename: google-chrome
        state: present

    - name: Install chrome
      apt: 
        name: google-chrome-stable 
        state: present

    - name: zoom dependencies
      apt:
        name:
          - libglib2.0-0
          - libgstreamer-plugins-base1.0-0
          - libxcb-shape0
          - libxcb-shm0
          - libxcb-xfixes0
          - libxcb-randr0
          - libxcb-image0
          - libfontconfig1
          - libgl1-mesa-glx
          - libxi6
          - libsm6
          - libxrender1
          - libpulse0
          - libxcomposite1
          - libxslt1.1
          - libsqlite3-0
          - libxcb-keysyms1
          - libxcb-xtest0
        state: present

    - name: Install zoom
      apt: 
        deb: https://zoom.us/client/latest/zoom_amd64.deb

    - name: Install asdf
      become: no
      command: git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf --branch v0.8.0
      args:
        creates: $HOME/.asdf/asdf.sh

    - name: asdf erlang deps
      apt:
        name:
          - build-essential 
          - autoconf 
          - m4 
          - libncurses5-dev 
          - libwxgtk3.0-gtk3-dev 
          - libgl1-mesa-dev 
          - libglu1-mesa-dev 
          - libpng-dev 
          - libssh-dev 
          - unixodbc-dev 
          - xsltproc 
          - fop 
          - libxml2-utils 
          - libncurses-dev 
          - openjdk-11-jdk
        state: present

    - name: Install asdf erlang
      become: no
      command: $HOME/.asdf/bin/asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
      args:
        creates: $HOME/.asdf/plugins/erlang
    
    - name: asdf elixir deps
      apt: 
       name: 
         - unzip
       state: present

    - name: Install asdf elixir
      become: no
      command: $HOME/.asdf/bin/asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
      args:
        creates: $HOME/.asdf/plugins/elixir

    - name: asdf ruby deps
      apt:
       name:
         - autoconf 
         - bison 
         - build-essential 
         - libssl-dev 
         - libyaml-dev 
         - libreadline6-dev 
         - zlib1g-dev 
         - libncurses5-dev 
         - libffi-dev 
         - libgdbm6 
         - libgdbm-dev 
         - libdb-dev
       state: present

    - name: install asdf ruby
      become: no
      command: $HOME/.asdf/bin/asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git
      args:
        creates: $HOME/.asdf/plugins/ruby

    - name: Copy file with owner and permissions
      become: no
      copy:
        src: /home/thiago/dev/thiamsantos/dotfiles/files/asdfrc
        dest: /home/thiago/.asdfrc

    - name: Install nvm
      shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"


