---
- name: Setup
  hosts: local
  become: true
  become_user: root
  environment:
    HOME: "/home/thiago"
  vars:
    go_tarball: "go1.15.3.linux-amd64.tar.gz"
    go_tarball_checksum: "sha256:010a88df924a81ec21b293b5da8f9b11c176d27c0ee3962dc1738d2352d3c02d"
    go_version_target: "go version go1.8.1 linux/amd64"
    go_download_location: "https://golang.org/dl/{{ go_tarball }}"
  tasks:
    - include: tasks/base.yml
    - include: tasks/spotify.yml
    - include: tasks/chrome.yml
    - include: tasks/zoom.yml
    - include: tasks/asdf.yml
    - include: tasks/node.yml
    - include: tasks/rust.yml
    - include: tasks/golang.yml
    - include: tasks/docker.yml
    - include: tasks/zsh.yml
    - include: tasks/vim.yml
    - include: tasks/vscode.yml
    - include: tasks/postgres.yml
    - include: tasks/apt.yml
    - include: tasks/redshift.yml
    - include: tasks/alacritty.yml
    - include: tasks/terraform.yml
    - include: tasks/awscli.yml
    - include: tasks/clamav.yml
    - include: tasks/i3.yml
