---
- name: Install asdf
  become: no
  command: "git clone https://github.com/asdf-vm/asdf.git {{ ansible_env.HOME }}/.asdf --branch v0.8.0"
  args:
    creates: "{{ ansible_env.HOME }}/.asdf/asdf.sh"

- name: asdf erlang deps
  apt:
    name:
      - build-essential
      - autoconf
      - m4
      - libncurses5-dev
      - libwxgtk3.0-gtk3-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libpng-dev
      - libssh-dev
      - unixodbc-dev
      - xsltproc
      - fop
      - libxml2-utils
      - libncurses-dev
      - openjdk-11-jdk
    state: present

- name: Install asdf erlang
  become: no
  command: "{{ ansible_env.HOME }}/.asdf/bin/asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git"
  args:
    creates: "{{ ansible_env.HOME }}/.asdf/plugins/erlang"

- name: asdf elixir deps
  apt:
   name:
     - unzip
   state: present

- name: Install asdf elixir
  become: no
  command: "{{ ansible_env.HOME }}/.asdf/bin/asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git"
  args:
    creates: "{{ ansible_env.HOME }}/.asdf/plugins/elixir"

- name: asdf ruby deps
  apt:
   name:
     - autoconf
     - bison
     - build-essential
     - libssl-dev
     - libyaml-dev
     - libreadline6-dev
     - zlib1g-dev
     - libncurses5-dev
     - libffi-dev
     - libgdbm6
     - libgdbm-dev
     - libdb-dev
   state: present

- name: install asdf ruby
  become: no
  command: "{{ ansible_env.HOME }}/.asdf/bin/asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git"
  args:
    creates: "{{ ansible_env.HOME }}/.asdf/plugins/ruby"

- name: Setup asdf configuration
  become: no
  copy:
    src: "{{ ansible_env.HOME }}/dev/thiamsantos/dotfiles/files/asdfrc"
    dest: "{{ ansible_env.HOME }}/.asdfrc"
