---
- name: Install xclip
  apt:
    name:
      - xclip
    state: present

- name: Create bin folder
  become: no
  file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory

- name: Create src folder
  become: no
  file:
    path: "{{ ansible_env.HOME }}/src"
    state: directory

- name: Install vlc
  apt:
    name: vlc
    state: present

- name: Install bluetooth tool
  apt:
    name:
      - bluez
      - bluez-tools
      - blueman
    state: present

- name: Install ffmpeg
  apt:
    name: ffmpeg
    state: present

- name: Install cheese
  apt:
    name: cheese
    state: present

- name: Install jq
  apt:
    name: jq
    state: present

- name: Install cowsay
  apt:
    name: cowsay
    state: present

- name: Install inotify-tools
  apt:
    name: inotify-tools
    state: present

# Increase number of watchers
- ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: '524288'
    sysctl_set: yes
    state: present
    reload: yes
