---
- name: Install xclip
  apt:
    name:
      - xclip
    state: present

- name: Create bin folder
  become: no
  file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory

- name: Install vlc
  apt:
    name: vlc
    state: present

- name: Install bluetooth tool
  apt:
    name:
      - bluez
      - bluez-tools
      - blueman
    state: present
