---
- name: Download the Go tarball
  get_url:
    url: "{{ go_download_location }}"
    dest: /usr/local/src/{{ go_tarball }}
    checksum: "{{ go_tarball_checksum }}"

- name: Extract the Go tarball
  unarchive:
    src: /usr/local/src/{{ go_tarball }}
    dest: /usr/local
    copy: no
    creates: /usr/local/go

- name: Install golero
  become: no
  shell: "go get -u github.com/thiamsantos/golero"
  args:
    creates: "{{ ansible_env.HOME }}/go/bin/golero"

- name: Install gololcat
  become: no
  shell: "go get -u github.com/thiamsantos/gololcat"
  args:
    creates: "{{ ansible_env.HOME }}/go/bin/gololcat"

- name: Install mkv2mp4
  become: no
  shell: "go get -u github.com/thiamsantos/mkv2mp4"
  args:
    creates: "{{ ansible_env.HOME }}/go/bin/mkv2mp4"
