---
- name: Add spotify signing key
  apt_key:
    url: https://download.spotify.com/debian/pubkey_0D811D58.gpg
    state: present

- name: Add Spotify repository
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    filename: spotify-client
    state: present

- name: Install spotify
  apt:
    name: spotify-client
    state: present
