---
- name: Install tmux deps
  apt:
    name:
      - libevent-dev
      - ncurses-dev
      - build-essential
      - bison
      - pkg-config
    state: present

- name: Install tmux
  apt:
   name: tmux
   state: present
   
- name: Create tmux plugins folder
  file:
    path: "{{ ansible_env.HOME }}/.tmux/plugins"
    state: directory

- name: Install tmux plugin manager
  become: no
  shell: "git clone https://github.com/tmux-plugins/tpm {{ ansible_env.HOME }}/.tmux/plugins/tpm"
  args:
    creates: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
    
- name: Install tmux-plugin-sysstat
  become: no
  shell: "git clone https://github.com/samoshkin/tmux-plugin-sysstat {{ ansible_env.HOME }}/.tmux/plugins/tmux-plugin-sysstat"
  args:
    creates: "{{ ansible_env.HOME }}/.tmux/plugins/tmux-plugin-sysstat"
    
- name: Install tmux-plugin-sysstat
  become: no
  shell: "git clone https://github.com/tmux-plugins/tmux-prefix-highlight {{ ansible_env.HOME }}/.tmux/plugins/tmux-prefix-highlight"
  args:
    creates: "{{ ansible_env.HOME }}/.tmux/plugins/tmux-prefix-highlight"

- name: Setup tmux.conf
  become: no
  file:
    src: "{{ ansible_env.HOME }}/dotfiles/files/tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    state: link
