---
- name: Install vim
  apt:
    name: vim
    state: present

- name: Install ag
  apt:
    name: silversearcher-ag
    state: present

- name: Download vim plug
  become: no
  shell: curl -fLo "{{ ansible_env.HOME }}/.vim/autoload/plug.vim" --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  args:
    creates: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"

- name: Setup vimrc
  become: no
  file:
    src: "{{ ansible_env.HOME }}/dev/thiamsantos/dotfiles/files/vimrc"
    dest: "{{ ansible_env.HOME }}/.vimrc"
    state: link

