---
- name: Install vscode
  apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64

- name: Create vscode config folder
  become: no
  file:
    path: "{{ ansible_env.HOME }}/.config/Code/User"
    state: directory

- name: Setup vscode settings
  become: no
  file:
    src: "{{ ansible_env.HOME }}/dotfiles/files/vscode-settings.json"
    dest: "{{ ansible_env.HOME }}/.config/Code/User/settings.json"
    state: link

- name: Install vscode editorconfig plugin
  become: no
  shell: code --install-extension editorconfig.editorconfig@0.15.1
  args:
    creates: "{{ ansible_env.HOME }}/.vscode/extensions/editorconfig.editorconfig-0.15.1"

- name: Install vscode erlang plugin
  become: no
  shell: code --install-extension pgourlain.erlang@0.6.7
  args:
    creates: "{{ ansible_env.HOME }}/.vscode/extensions/pgourlain.erlang-0.6.7"

- name: Install vscode terraform plugin
  become: no
  shell: code --install-extension hashicorp.terraform@2.3.0
  args:
    creates: "{{ ansible_env.HOME }}/.vscode/extensions/hashicorp.terraform-2.3.0"

- name: Install vscode material theme
  become: no
  shell: code --install-extension woodywoodsta.vscode-material-syntax-dark@0.1.1
  args:
    creates: "{{ ansible_env.HOME }}/.vscode/extensions/woodywoodsta.vscode-material-syntax-dark-0.1.1"

- name: Install vscode pgformatter plugin
  become: no
  shell: code --install-extension bradymholt.pgformatter@1.16.0
  args:
    creates: "{{ ansible_env.HOME }}/.vscode/extensions/bradymholt.pgformatter-1.16.0"

- name: Install vscode sass plugin
  become: no
  shell: code --install-extension syler.sass-indented@1.8.13
  args:
    creates: "{{ ansible_env.HOME }}/.vscode/extensions/syler.sass-indented-1.8.13"

- name: Install vscode sublime keybindings plugin
  become: no
  shell: code --install-extension ms-vscode.sublime-keybindings@4.0.7
  args:
    creates: "{{ ansible_env.HOME }}/.vscode/extensions/ms-vscode.sublime-keybindings-4.0.7"

- name: Install vscode elixir plugin
  become: no
  shell: code --install-extension mjmcloug.vscode-elixir@1.1.0
  args:
    creates: "{{ ansible_env.HOME }}/.vscode/extensions/mjmcloug.vscode-elixir-1.1.0"

- name: Install yaml plugin
  become: no
  shell: code --install-extension redhat.vscode-yaml@0.13.0
  args:
    creates: "{{ ansible_env.HOME }}/.vscode/extensions/redhat.vscode-yaml-0.13.0"
