[icons]
icons = "awesome4"

[theme]
theme = "/home/thiago/.config/i3status-rust/theme.toml"

[[block]]
block = "music"
format = " $icon {$title by $artist|} "
player = "spotify"

[[block]]
block = "sound"

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization "

[[block]]
block = "memory"
format = " $icon $mem_used ($mem_used_percents) "

[[block]]
block = "memory"
format = " $icon_swap $swap_used ($swap_used_percents) "

[[block]]
block = "bluetooth"
mac = "AC:80:0A:0D:DC:3B"
format = " $icon XM5 "

[[block]]
block = "battery"
device = "BAT0"

[[block]]
block = "battery"
device = "hidpp_battery_0"


[[block]]
block = "custom"
interval = "once"
command = "echo \"WEEK $(date '+%U')\""

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%a %d/%m %R', l:pt_BR) "
