idle_bg = "#1D1F21"
idle_fg = "#E5E5E5"
info_bg = "#1D1F21"
info_fg = "#E5E5E5"
good_bg = "#1D1F21"
good_fg = "#00CD00"
warning_bg  = "#1D1F21"
warning_fg  = "#CDCD00"
critical_bg = "#1D1F21"
critical_fg = "#CD0000"
separator = "|"
separator_bg = "#1D1F21"
separator_fg = "#666666"
