idle_bg = "#1c1f24"
idle_fg = "#e5e5e5"
info_bg = "#1c1f24"
info_fg = "#e5e5e5"
good_bg = "#1c1f24"
good_fg = "#98be65"
warning_bg  = "#1c1f24"
warning_fg  = "#ECBE7B"
critical_bg = "#1c1f24"
critical_fg = "#ff6c6b"
separator = "|"
separator_bg = "#1c1f24"
separator_fg = "#666666"
