idle_bg = "#282c34"
idle_fg = "#e5e5e5"
info_bg = "#282c34"
info_fg = "#e5e5e5"
good_bg = "#282c34"
good_fg = "#98be65"
warning_bg  = "#282c34"
warning_fg  = "#ECBE7B"
critical_bg = "#282c34"
critical_fg = "#ff6c6b"
separator = "|"
separator_bg = "#282c34"
separator_fg = "#666666"
