idle_bg = "#282a36"
idle_fg = "#f8f8f2"
info_bg = "#282a36"
info_fg = "#f8f8f2"
good_bg = "#282a36"
good_fg = "#50fa7b"
warning_bg  = "#282a36"
warning_fg  = "#ffb86c"
critical_bg = "#282a36"
critical_fg = "#ff5555"
separator = "|"
separator_bg = "#282a36"
separator_fg = "#e2e2dc"
