#!/usr/bin/env sh

set -e

lock() {
  img=/tmp/i3lock.png

  scrot -o $img
  convert $img -scale 10% -scale 1000% $img

  i3lock -e -i $img
}

switch_wallpaper() {
  feh --randomize --bg-fill --no-fehbg ~/wallpapers/*
}

setup_monitor() {
  if xrandr | grep "HDMI-1 connected"
  then
    xrandr --output HDMI-1 --primary --auto --output eDP-1 --off
  fi

  switch_wallpaper
}

switch_monitor() {
  if xrandr | grep "HDMI-1 connected primary"
  then
    xrandr --output eDP-1 --primary --auto --output HDMI-1 --off
  else
    xrandr --output HDMI-1 --primary --auto --output eDP-1 --off
  fi

  switch_wallpaper
}

switch_headphone() {
  device="38:18:4C:2B:F5:A8"

  if bluetoothctl info $device | grep "Connected: yes"
  then
    bluetoothctl disconnect $device
  else
    bluetoothctl connect $device
  fi
}

rofi_systemctl() {
  chosen=$(echo "[Cancel]\nLock\nLogout\nSuspend\nHibernate\nReboot\nShutdown" | rofi -dmenu -i)

  case $chosen in
    Lock)
      lock
      ;;
    Logout)
      i3-msg exit
      ;;
    Suspend)
      lock && systemctl suspend
      ;;
    Hibernate)
      lock && systemctl suspend
      ;;
    Reboot)
      systemctl reboot
      ;;
    Shutdown)
      systemctl poweroff -i
      ;;
    *)
      exit 0
      ;;
  esac
}

rofi_i3_hotkeys() {
  "$HOME"/dotfiles/files/rofi-i3-hotkeys.py
}

rofi_kill() {
  all_pids="$(ps exa)"
  pid_line=$( (echo "${all_pids}")  | rofi -dmenu -i -p "Kill process")
  pid=$(echo "$pid_line" | awk '{print $1}')

  if [ -z "$pid" -o "$pid" = "PID" ]
  then
    return 0
  else
    SUDO_ASKPASS="$HOME/dotfiles/files/rofi-ask-password.sh" sudo -A kill -9 "$pid"
  fi
}

dot_help() {
  echo "
Dotfile CLI.

Usage: dot [command] [args]

Commands:
  lock             Lock screen
  rofi_i3_hotkeys  Show i3 hotkeys via rofi
  rofi_kill        Kill a running process via rofi
  rofi_systemctl   Lock, reboot, shutdown via rofi
  setup_monitor    Enable HDMI and turn off laptop screen
  switch_headphone Connect headphone
  switch_monior    Switch between HDMI and laptop screen
  switch_wallpaper Switch the wallpaper
  *                Help

Examples:
  $ dot lock
  $ dot setup_monitor
  $ dot rofi_systemctl
"
  exit 1
}

case "$1" in
lock)
  lock
  ;;
switch_headphone)
  switch_headphone
  ;;
setup_monitor)
  setup_monitor
  ;;
switch_monitor)
  switch_monitor
  ;;
switch_wallpaper)
  switch_wallpaper
  ;;
rofi_systemctl)
  rofi_systemctl
  ;;
rofi_i3_hotkeys)
  rofi_i3_hotkeys
  ;;
rofi_kill)
  rofi_kill
  ;;
*)
  dot_help
  ;;
esac
