" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
      \| PlugInstall --sync | source $MYVIMRC
      \| endif

call plug#begin()

Plug 'tpope/vim-sensible'
Plug 'vim-airline/vim-airline'
Plug 'sheerun/vim-polyglot'
Plug 'google/vim-searchindex'
Plug '~/.fzf'
Plug 'junegunn/fzf.vim'
Plug 'preservim/nerdtree'

call plug#end()

" Switch syntax highlighting on
syntax on

" Use 2 spaces instead of tabs
set expandtab
set softtabstop=2
set tabstop=2
set shiftwidth=2

" Use colors that look good on a dark background
set background=dark

" Absolute line numbers
set nu

" Store swap file elsewhere
set directory=$HOME/.vim/swp//

" Disable backup files
set nobackup
set nowritebackup

" Enable highlighting and stripping whitespace on save by default
let g:better_whitespace_enabled=1
let g:strip_whitespace_on_save=1

" Highlight search
set hlsearch

" Break line in convenient places
set linebreak

" Enable airline tabline
let g:airline#extensions#tabline#enabled = 1

" Enable persistent undo
set undofile
set undodir=~/.vim/undodir

" Centralize matches of search
nnoremap n nzz
nnoremap N Nzz

" Split right and below
set splitright
set splitbelow

" make . to work with visually selected lines
vnoremap . :normal.<CR>

" Fuzzy find
let g:fzf_preview_window = []

set foldenable
set foldlevelstart=10
set foldnestmax=10
set foldmethod=indent

" highlight trailing whitespace
match ErrorMsg '\s\+$'
" remove trailing whitespaces automatically
autocmd BufWritePre * :%s/\s\+$//e

" Map space to leader
let mapleader = "\<Space>"

nnoremap <Leader>p :GFiles<CR>
nnoremap <Leader>w :w<CR>
nnoremap <Leader>n :bnext<CR>
nnoremap <Leader>b :bprevious<CR>
nnoremap <Leader>r :source $MYVIMRC<CR>
nnoremap <Leader>v :vs<CR>
nnoremap <Leader>s :sp<CR>
nnoremap <Leader>o :on<CR>
nnoremap <Leader>q :bd<CR>
nnoremap <Leader>l <C-W>l
nnoremap <Leader>k <C-W>k
nnoremap <Leader>j <C-W>j
nnoremap <Leader>h <C-W>h
nnoremap <Leader>x <C-W>q
nnoremap <Leader>f :NERDTreeToggle<CR>
