call plug#begin()

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-sensible'
Plug 'vim-airline/vim-airline'
Plug 'terryma/vim-multiple-cursors'
Plug 'editorconfig/editorconfig-vim'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-eunuch'
Plug 'ntpeters/vim-better-whitespace'
Plug 'sheerun/vim-polyglot'
Plug 'vim-scripts/vim-auto-save'
Plug 'rstacruz/vim-closer'
Plug 'andymass/vim-matchup'
Plug 'tpope/vim-dispatch'
Plug 'janko/vim-test'
Plug 'wellle/tmux-complete.vim'
Plug 'mhinz/vim-startify'
Plug 'Yggdroot/indentLine'
Plug 'google/vim-searchindex'
Plug 'RRethy/vim-illuminate'

call plug#end()

syntax on

" Use 2 spaces instead of tabs
set expandtab
set softtabstop=2
set tabstop=2
set shiftwidth=2

" Use colors that look good on a dark background
set background=dark

" Absolute line numbers
set nu

" Disable swap files
set noswapfile

" Some servers have issues with backup files, see #649
set nobackup
set nowritebackup

" You will have bad experience for diagnostic messages when it's default 4000.
set updatetime=300

" don't give |ins-completion-menu| messages.
set shortmess+=c

" always show signcolumns
set signcolumn=yes

let test#strategy = "dispatch"
let mapleader="\\"
let g:strip_whitespace_on_save=1
let g:auto_save = 1
let g:auto_save_in_insert_mode = 0
let g:indent_guides_enable_on_vm_startup = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t'

" Disable arrow keys
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

" Disable Page up/down keys
noremap <PageUp> <Nop>
noremap <PageDown> <Nop>

map <Leader>p :FZF<CR>
map <Leader>f :Ag<CR>

" Use <c-space> to trigger completion.
inoremap <silent><expr> <c-space> coc#refresh()

nmap <leader>h :bprevious<cr>
nmap <leader>q :bdelete<cr>

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
