export TERM="xterm-256color"
export HOME="/home/thiago"
export ZSH=$HOME/.oh-my-zsh

fpath+=$HOME/.zsh_functions

ZSH_THEME="robbyrussell"

plugins=(
  zsh-syntax-highlighting
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# fzf
[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

nvm alias default 12.19.0 > /dev/null

autoload -U add-zsh-hook
load-nvmrc() {
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install > /dev/null
    elif [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm use > /dev/null
    fi
  elif [ "$node_version" != "$(nvm version default)" ]; then
    nvm use default > /dev/null
  fi
}
add-zsh-hook chpwd load-nvmrc
load-nvmrc

# terraform
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/bin/terraform terraform

# yvm
export YVM_DIR=$HOME/.yvm
[ -r $YVM_DIR/yvm.sh ] && . $YVM_DIR/yvm.sh

# asdf
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

# go
export GOPATH=$HOME/go
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:/usr/local/go/bin"

# rust
export PATH="$PATH:$HOME/.cargo/bin"

# iex history
export ERL_AFLAGS="-kernel shell_history enabled"

export PATH="$PATH:$HOME/bin"
export PATH="$PATH:$HOME/.local/bin"
export EDITOR="vim"

# bind home/end keys
bindkey "${terminfo[khome]}" beginning-of-line
bindkey "${terminfo[kend]}" end-of-line

# aliases
alias ga="git add"
alias gap="git add -p"
alias gc="git commit -m"
alias gca="git commit --amend --no-edit"
alias gm="git merge"
alias gck="git checkout"
alias gpl="git pull --rebase"
alias gp="git push origin HEAD"
alias gpf="git push origin HEAD --force-with-lease"
alias gb="git checkout -b"
alias gmb="git symbolic-ref --short refs/remotes/origin/HEAD | sed 's@^origin/@@'"
alias gs="git status"

gsync() {
  local main_branch="$(gmb)"

  gck "$main_branch" && gpl && gck - && gm "$main_branch"
}

alias xclip="xclip -selection c"

# tmux
if [[ $DISPLAY ]]; then
  [[ $- != *i* ]] && return
  [[ -z "$TMUX" ]] && exec tmux
fi
