export TERM="xterm-256color"
export HOME="/home/thiago"
export ZSH=$HOME/.oh-my-zsh

fpath+=$HOME/.zsh_functions

ZSH_THEME="dracula"

source $HOME/src/dracula-zsh-syntax-highlighting/zsh-syntax-highlighting.sh

plugins=(
  zsh-syntax-highlighting
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh
autoload -U add-zsh-hook

# fzf
[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh

# terraform
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/bin/terraform terraform

# asdf
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

# yvm
export YVM_DIR=$HOME/.yvm
[ -r $YVM_DIR/yvm.sh ] && . $YVM_DIR/yvm.sh

# go
export GOPATH=$HOME/go
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:/usr/local/go/bin"

# rust
export PATH="$PATH:$HOME/.cargo/bin"

# iex history
export ERL_AFLAGS="-kernel shell_history enabled"
export KERL_CONFIGURE_OPTIONS="--disable-debug --without-javac"

export PATH="$PATH:$HOME/bin"
export PATH="$PATH:$HOME/.local/bin"
export EDITOR="vim"

export FZF_DEFAULT_COMMAND="ag -g ''"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# doom emacs
export PATH="$PATH:$HOME/.emacs.d/bin"

# bind home/end keys
bindkey "${terminfo[khome]}" beginning-of-line
bindkey "${terminfo[kend]}" end-of-line

# direnv
eval "$(direnv hook zsh)"

# aliases
alias ga="git add"
alias gap="git add -p"
alias gc="git commit -m"
alias gca="git commit --amend --no-edit"
alias gm="git merge"
alias gck="git checkout"
alias gpl="git pull --rebase"
alias gp="git push origin HEAD"
alias gpf="git push origin HEAD --force-with-lease"
alias gb="git checkout -b"
alias gmb="git symbolic-ref --short refs/remotes/origin/HEAD | sed 's@^origin/@@'"
alias gs="git status"
alias gcb="git rev-parse --abbrev-ref HEAD"

gsup() {
  local current_branch="$(gcb)"

  git branch --set-upstream-to="origin/$current_branch" "$current_branch"
}

gsync() {
  local main_branch="$(gmb)"

  gck "$main_branch" && gpl && gck - && gm "$main_branch"
}

grsync() {
  local main_branch="$(gmb)"

  gck "$main_branch" && gpl && gck - && git rebase "$main_branch"
}

alias xclip="xclip -selection c"
alias mt="mix format && mix test && mix credo"
alias swapclear="sudo swapoff -a && sudo swapon -a"

encrypt_value() {
  echo -n "Enter value: "
  stty -echo
  read value
  echo
  stty echo

  echo -n "Enter secret: "
  stty -echo
  read secret
  echo
  stty echo

  echo $value | openssl aes-256-cbc -a -salt -k $secret -pbkdf2 | xclip
  echo 'Encrypted value copied to clipboard!'
}

decrypt_value() {
  echo -n "Enter encrypted value: "
  stty -echo
  read encrypted_value
  echo
  stty echo

  echo -n "Enter secret: "
  stty -echo
  read secret
  echo
  stty echo

  echo $encrypted_value | openssl aes-256-cbc -d -a -k $secret -pbkdf2 | xclip
  echo 'Value copied to clipboard!'
}

genpasswd() {
  local size=${1:-64}

  strings /dev/urandom | grep -o '[[:alnum:]]' | head -n $size | tr -d '\n'
}

. $HOME/.ham/completion/bash/_ham
