export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

plugins=(
  zsh-syntax-highlighting
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

autoload -U promptinit; promptinit
prompt pure > /dev/null

# fzf
[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# yvm
export YVM_DIR=$HOME/.yvm
[ -r $YVM_DIR/yvm.sh ] && . $YVM_DIR/yvm.sh

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# asdf
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

# java
export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
export PATH="$PATH:/opt/gradle/gradle-4.8.1/bin"
export PATH="$PATH:$JAVA_HOME/bin"

# rust
export PATH="$HOME/.cargo/bin:$PATH"

# go
export PATH="$PATH:/usr/local/go/bin"
export GOPATH=$HOME/go

# iex history
export ERL_AFLAGS="-kernel shell_history enabled"

export PATH="$PATH:$HOME/bin"
export TERM="xterm-256color"
export EDITOR="vim"

# bind home/end keys
bindkey "${terminfo[khome]}" beginning-of-line
bindkey "${terminfo[kend]}" end-of-line

# aliases
alias ga="git add"
alias gap="git add -p"
alias gc="git commit -m"
alias gm="git merge"
alias gck="git checkout"
alias gpl="git pull --rebase"
alias gp="git push origin HEAD"
alias gpf=" git push origin HEAD --force-with-lease"
alias gb="git checkout -b"
alias gsync="gck master && gpl && gck - && gm master"

# tmuxinator
source $HOME/bin/tmuxinator.zsh

# tmux
if [[ $DISPLAY ]]; then
  [[ $- != *i* ]] && return
  [[ -z "$TMUX" ]] && exec tmux
fi
