export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

plugins=(
  zsh-syntax-highlighting
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

autoload -U promptinit; promptinit
prompt pure > /dev/null

# fzf
[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

nvm alias default 10.16.3 > /dev/null

# yvm
export YVM_DIR=$HOME/.yvm
[ -r $YVM_DIR/yvm.sh ] && . $YVM_DIR/yvm.sh

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# asdf
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

# go
export GOPATH=$HOME/go
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:/usr/local/go/bin"

# iex history
export ERL_AFLAGS="-kernel shell_history enabled"

export PATH="$PATH:$HOME/bin"
export TERM="xterm-256color"
export EDITOR="vim"

# bind home/end keys
bindkey "${terminfo[khome]}" beginning-of-line
bindkey "${terminfo[kend]}" end-of-line

# confluent kafka
export PATH="$PATH:$HOME/confluent/bin"

# aliases
alias ga="git add"
alias gap="git add -p"
alias gc="git commit -m"
alias gm="git merge"
alias gck="git checkout"
alias gpl="git pull --rebase"
alias gp="git push origin HEAD"
alias gpf=" git push origin HEAD --force-with-lease"
alias gb="git checkout -b"
alias gsync="gck master && gpl && gck - && gm master"
alias gs="git status"

# tmuxinator
source $HOME/bin/tmuxinator.zsh

# tmux
if [[ $DISPLAY ]]; then
  [[ $- != *i* ]] && return
  [[ -z "$TMUX" ]] && exec tmux
fi
